version: "3.9"

services:

  db:
    image: postgres
    container_name: dwh-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      - dwh-network
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=Passw0rd!.
  
  dbms:
  # you can use `docker inspect <db_container_ID> | grep IPAddress` to register the db to the dbms service in PgAdmin console
  # or you can set `host.docker.internal` for connection host on pgAdmin
    image: dpage/pgadmin4
    container_name: dwh-dbms
    restart: unless-stopped
    ports:
      - "5435:5435"
    networks:
      - dwh-network
    environment:
      - PGADMIN_LISTEN_PORT=5435
      - PGADMIN_DEFAULT_PASSWORD=Passw0rd!.
      - PGADMIN_DEFAULT_EMAIL=info@baysansoft.com

volumes:
  db_volume:

networks:
  dwh-network:
    driver: bridge
